language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/parallel-lint --exclude vendor .
  - ./vendor/bin/phpunit --configuration phpunit.xml tests/
  - ./var-dump-check src
